# Generated by Django 3.2.9 on 2024-07-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_item',
            new_name='title',
        ),
    ]
