# Generated by Django 3.2.9 on 2024-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_proj', '0002_rename_todo_item_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='ifcompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='tasktodo',
        ),
    ]
